update comments for ModToggleDelegates from #83
hk-modding/api pull request #87
Opened 2021-11-26 20:01 UTC by TheMulhima

2021-11-29 18:38 UTC, fifty-six commented
Can you suppress the warnings caused by adding the Obsolete annotation? Rest looks fine.

2021-12-04 06:29 UTC, TheMulhima commented
I'm not sure how to do that

2021-12-14 13:44 UTC, mandar1jn commented
I have created a pr to the Mulhima's fork adding pragma directives to ignore the warnings

2021-12-16 20:35 UTC, fifty-six requested changes

2021-12-16 20:35 UTC, fifty-six commented on Assembly-CSharp/ModListMenu.cs
>                  ApplyChange: var applyChange
missing the pragma here

2021-12-16 20:41 UTC, fifty-six commented
Actually #89 does this anyways, including this pr.

2021-12-16 20:42 UTC, closed without merging