Fix GetAllMods method
hk-modding/api pull request #96
Opened 2022-01-20 10:00 UTC by flibber-hk

2022-01-20 10:03 UTC, SFGrenade commented
here we see a description like "make the method do what the comment says".

2022-01-20 10:15 UTC, flibber-hk commented
If you prefer, I could have changed the comment to something like

        /// <param name="onlyEnabled">Should the iterator exclude enabled mods, despite the parameter name</param>
        /// <param name="allowLoadError">Should the iterator exclude contain mods which don't have load errors, despite the parameter name</param>

2022-01-22 22:57 UTC, fifty-six requested changes

2022-01-22 22:57 UTC, fifty-six commented on Assembly-CSharp/ModHooks.cs
> +            .Where(x => !(onlyEnabled && !x.Enabled || !allowLoadError && x.Error != null))
Simplify the conditional to like `(x.Enabled || !onlyEnabled) && (x.Error != null || allowLoadError)` or `(!onlyEnabled || x.Enabled) && (allowLoadError || x.Error != null)` please. The nested nots are hard to read.

2022-01-22 22:59 UTC, fifty-six commented
If you want, you could change the parameter name to something like `allowDisabled` and then use `allowDisabled` instead of `!onlyEnabled`, because it doesn't seem like this is in-use anywhere as far as I can tell from a cursory github search. Up to you though.

2022-01-23 07:40 UTC, flibber-hk commented
I was copying the style from the GetMod methods, so I changed those too in the latest commit. Parameter name `allowDisabled` is probably slightly better but I don't really feel it's worth changing (I don't have a strong opinion on this though)

2022-01-23 16:44 UTC, merged